# -*- coding: utf-8 -*-
"""SceneUnderstanding_CLIP_OpenAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w9U8VLmPo7wLp5YizHTDFOF4snRDodrW
"""

import torch
from PIL import Image
from transformers import CLIPProcessor, CLIPModel
import requests

class SceneUnderstandingWithCLIP:
    def __init__(self):
        self.processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")
        self.model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
        self.model.to("cuda")
        self.img_url = 'https://www.mixedmartialarts.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_700/MTg3NzUxNDMzMDM0OTM0MjQx/us-army-soldier-vs-israeli-soldier-in-knife-fight-contest.webp'
        self.raw_image = Image.open(requests.get(self.img_url, stream=True).raw).convert("RGB")

    def generate_caption(self, text_prompts):
        """
        Generates a similarity score for each text prompt and returns the best matching caption.
        :param text_prompts: List of textual descriptions to match with the image.
        :return: Best matching text description.
        """
        inputs = self.processor(
            text=text_prompts, images=self.raw_image, return_tensors="pt", padding=True
        ).to("cuda")

        # Compute similarity scores
        outputs = self.model(**inputs)
        logits_per_image = outputs.logits_per_image  # Image-to-text scores
        probs = logits_per_image.softmax(dim=1)  # Normalize scores to probabilities

        # Find the best match
        best_idx = probs.argmax(dim=1).item()
        return text_prompts[best_idx], probs[0, best_idx].item()

    def classify_crime(self, caption):
        crime_keywords = ["crime", "weapon", "gun", "knife", "violence", "fight", "blood"]
        if any(keyword in caption.lower() for keyword in crime_keywords):
            return "Crime detected"
        return "No crime"

    def save_model(self, save_dir):
        self.model.save_pretrained(save_dir)
        self.processor.save_pretrained(save_dir)

if __name__ == "__main__":
    scene_understanding = SceneUnderstandingWithCLIP()

    # Define possible captions
    text_prompts = [
        "a photograph of a peaceful park",
        "a crime scene with a weapon",
        "a family having a picnic",
        "a busy street with cars",
        "a violent fight between people",
    ]

    # Generate caption
    best_caption, confidence = scene_understanding.generate_caption(text_prompts)
    print(f"Caption: {best_caption} (Confidence: {confidence:.2f})")
    print(scene_understanding.classify_crime(best_caption))